name: "[Call] Run this action-action manually"

run-name: Run action-action

on:
  workflow_call:

jobs:
  run-action:
    runs-on: arc-runner-set
    name: Run action-action
    steps:
      - uses: organisation/action-action@v1
